### ISSUE TITLE
Support workspace snippets

### ISSUE THREAD

**Issue by tennox** [robole/vscode-snippets-ranger#4]
Wonderful extension! :heart:
Only thing I miss: since ~2 years one can define workspace snippets in VSCode:
https://stackoverflow.com/a/56978528/1633985

Would be awesome if this extension would support that :sunglasses:

**Comment by robole** [comment]
hi @tennox 

I am glad you like the extension. Is it worthy of a star? ⭐ 😉

I haven't had a reason to add workspace-specific snippets to any of my projects, which is why I didn't add it as a feature to the extension already! For now, I will leave this open as an enhancement, if others are interested in this feature, they can give a 👍 to this comment.

I am open to a PR  if someone is interested in picking it up? However, I have a reservation about  [mutli-root workspaces](https://code.visualstudio.com/docs/editor/workspaces#_multiroot-workspaces), they need to be considered too. I would not like this feature to degrade performance.  I don't have experience with that part of the API. So, let's have a chat about it before any code is written.

all the best,

rob

**Comment by robole** [comment]
Workspace (Project) snippets has been **added in v25.1**.

If there is any problem  @tennox , raise an issue to let me know, thanks.
